name: ðŸ“„ License check

on:
    workflow_call:
        inputs: {}

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
    PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
    TF_APPEND_USER_AGENT: pulumi

jobs:
    license_check:
        runs-on: ubuntu-latest
        steps:
            - name: ðŸ“¦ Checkout repo
              uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - name: ðŸ”§ Setup tools
              uses: ./.github/actions/setup-tools
              with:
                  tools: go
                  cache-go: false
            - name: ðŸ”§ Prepare local workspace
              run: make prepare_local_workspace
              continue-on-error: true
            - name: ðŸ“„ Check licenses
              uses: pulumi/license-check-action@main
              with:
                  module-path: provider
                  ignore-modules: >-
                      github.com/aead/chacha20,
                      github.com/apache/arrow/go/v12,
                      github.com/apache/thrift/lib/go/thrift,
                      github.com/cloudflare/circl,
                      github.com/golang,
                      github.com/gorhill/cronexpr,
                      github.com/in-toto/in-toto-golang,
                      github.com/jmespath/go-jmespath,
                      github.com/keybase/go-crypto,
                      github.com/klauspost/compress,
                      github.com/mattn/go-localereader,
                      github.com/modern-go/reflect2,
                      github.com/pierrec/lz4,
                      github.com/pjbgf/sha1cd,
                      github.com/pulumi,
                      github.com/segmentio/asm,
                      golang.org
